global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mi_web_api'
    scheme: 'https'  # Sigue usando https si es necesario
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['192.168.18.78:44303']
